beli_ikan/urls.py
from django.urls import path
from . import views

app_name = "beli_ikan"
urlpatterns = [
    path('', views.daftar_ikan_view, name="form_ikan"),
    path('terima', views.buat_ikan_view, name="terima"),
    path('delete/<id>', views.hapus_Ikan, name="hapus"),
    path('datajson', views.ambil_data_json, name="ambil_data"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.blog_view, name="blog_view"),
    path('buat', views.buat_blog, name="form_blog"),
    path('delete/<id>', views.blog_delete, name="hapus"),
    path('webservice', views.webservice, name="json_webservice"),
]

faq/urls.py
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
    path('', views.faq_view, name="faq"),
    path('webservice/', views.webservice, name="json_webservice"),
]

home_app/urls.py
from django.urls import path
from . import views

app_name = "home_app"
urlpatterns = [
    path('', views.homeView, name="beranda"),
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name='logout'),
]

tk2_eclair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('blog/', include('blog.urls') ),
    path('toko/', include('toko.urls'), name="pathToko"),
    path('beli/', include('beli_ikan.urls')),
    path('faq/', include('faq.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path, include, re_path
from .views import *

app_name="toko"
urlpatterns = [
    path('', displayToko, name="home_toko"),
    path('tambah/', tambahToko),
    path('tambah/buat/', buat),
    path('hapus/', hapusTok),
	path("jsontoko", returnJson)

]

home_app/models.py
from django.db import models

# Create your models here.

home_app/forms.py
from django import forms
from django.forms.widgets import PasswordInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    last_name = forms.CharField(max_length=30, required=False, help_text='Please enter your name')
    email = forms.EmailField(max_length=254, help_text='Please type your email address')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30, required=True, help_text='Please enter your username')
    password = forms.CharField(max_length=30, required=True, help_text='Please enter your password', widget=PasswordInput)

home_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from home_app.forms import RegisterForm, LoginForm

# Create your views here.
def homeView(request):
    return render(request, "beranda.html")

def register_view(request):
    if request.method == 'POST':
        form_regis = RegisterForm(request.POST)
        if form_regis.is_valid():
            form_regis.save()
            username = form_regis.cleaned_data.get('username')
            raw_password = form_regis.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form_regis = RegisterForm()
    return render(request, "register.html", {'form': form_regis})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        form = LoginForm()
        if request.method == "POST":
            form = LoginForm(request=request,data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request,user=user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                return redirect('/')
            else:
                return render(request, "login.html", {'form': form})
        return render(request, "login.html", {'form': form})

def logout_view(request):
    logout(request)
    return redirect("/")

@login_required(login_url='/login')
def restricted_view(request):
    return render(request, "restricted.html")

home_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home_style.css' %}">
    <title>{% block title %}{% endblock %} - Eclair Lake</title>
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-light navbar-expand-md bg-light justify-content-center">
        <button class="navbar-toggler ml-1" type="button" data-toggle="collapse" data-target="#collapsingNavbar2">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-between align-items-center w-100" id="collapsingNavbar2">
            <ul class="navbar-nav mx-auto text-center">
                {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item {% if url_name == 'form_ikan' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'beli_ikan:form_ikan' %}">Beli</a>
                </li>
                <li class="nav-item {% if url_name == 'home_toko' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'toko:home_toko' %}">Toko</a>
                </li>
                <li class="nav-item {% if url_name == 'blog_view' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'blog:blog_view' %}">Blog</a> 
                </li>
                <a href="{% url 'home_app:beranda' %}" class="{% if url_name == 'beranda' %} active {% endif %}"><img class="logo-navbar" src="{% static 'images/logo-eclair.png' %}"></a>
                <li class="nav-item {% if url_name == 'faq' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'faq:faq' %}">FAQ</a> 
                </li>
                {% if not user.is_authenticated %} 
                    <li class="nav-item {% if url_name == 'register' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home_app:register' %}">Register</a>
                    </li>
                    <li class="nav-item {% if url_name == 'login' %} active {% endif %}">
                        <a class="nav-link" href="{% url 'home_app:login' %}">Login</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link"> Halo {{user.first_name}} {{user.last_name}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'home_app:logout' %}> Logout </a>
                    </li>
                {% endif %}
                {% endwith %}
            </ul>
        </div>
    </nav>
            
    {% block isi %}{% endblock %}

    <div class="footer" id="footer">
        <p id="copri">©Eclair-lake</p>
        <div class="logo">
            <a href="https://id-id.facebook.com/"><img class="logo-item" src="{% static 'images/FB.png' %}"></a>
            <a href="https://www.instagram.com/"><img class="logo-item" src="{% static 'images/IG.png' %}"></a>
            <a href="https://id.linkedin.com/"><img class="logo-item" src="{% static 'images/LinkedIN.png' %}"></a>
            <a href="https://wa.me/"><img class="logo-item" src="{% static 'images/WA.png' %}"></a>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
</body>
<div class="se-pre-con"></div>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script></body>
</html>

home_app/templates/beranda.html
{% extends "base.html" %}
{% load static %}

{% block title %} Beranda {% endblock %}

{% block head %}
<link href="https://fonts.googleapis.com/css?family=Poppins:400,400i&display=swap" rel="stylesheet"> 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="{% static 'homskrip.js' %}"></script>
{% endblock %}

{% block isi %}
<div id="loading">
</div> 
<div class=".container nelayan">
    <div class="text text-center">
        <h1>Ikan<br>Segar?</h1>
    </div>    
</div>

<div class="container-fluid bg-biru">
    <div class="ikan-float">
        <img src="{% static 'images/ikan_desc_eclair.png' %}">
    </div>
    <div class="row">
        <div class="col text-ikan ukur">
            <h1>Apa itu Eclair?</h1>
            <p>Eclair adalah sebuah website yang memfasilitasi transaksi 
                antara nelayan dengan pembeli ikan.</p>
        </div>
    </div>
    
</div>

<div class="container-fluid full-layar">
    <div class="row">
        <div class="col-6 text-kenapa ukur">
            <h1>Mengapa Eclair?</h1>
            <p>Karena dengan Eclair, anda akan mendapatkan ikan segar langsung dari nelayan.   Eclair juga menyediakan informasi atau fakta mengenai ikan bagi anda yang masih bingung ingin membeli ikan apa.</p>
        </div>
        <div class="col-6 penuhin">
        </div>
    </div>
</div>

<div class="container-fluid bg-biru display-centered ujung-bawah">
    <h1 class="tengah-tengah">Testimoni pengguna Eclair</h1>
    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <p class="card-text">Ikan yang disediakan Eclair sangat segar dan pengantarannya pun tepat waktu. </p>
                <p class="card-text"></p>
                <p class="card-text">Terima kasih Eclaire!</p>
                <p class="card-text">Pengguna1</p>
            </div>
        </div>
    </div>
</div>
{% endblock isi %}

home_app/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block isi %}
<div class="container-fluid header">
    <h1>TK 2</h1>
</div>

<div class="container-fluid">
    <div class="row regisbackground">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h4>Login, Let's Go!</h4>
            <form action="{% url 'home_app:login' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" id="btn_login" type="submit">Login</button>
                </div>
            </form>
            <p>Didn't have an account? <a href="{% url 'home_app:register' %}">Register Now</a></p>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock isi %}

home_app/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Register{% endblock title %}

{% block isi %}
<div class="container-fluid header">
    <h1>TK 2</h1>
</div>

<div class="container-fluid">
    <div class="row regisbackground">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h4>Register Now</h4>
            <form action="{% url 'home_app:register' %}" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                    </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Sign Up</button>
                </div>
            </form>
            <p>Already have an account? <a href="{% url 'home_app:login' %}">Login</a></p>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock isi %}