beli_ikan/urls.py
from django.urls import path
from . import views

app_name = "beli_ikan"
urlpatterns = [
    path('', views.daftar_ikan_view, name="form_ikan"),
    path('terima', views.buat_ikan_view, name="terima"),
    path('delete/<id>', views.hapus_Ikan, name="hapus"),
    path('datajson', views.ambil_data_json, name="ambil_data"),
]

faq/urls.py
from django.urls import path
from . import views

app_name = "faq"
urlpatterns = [
    path('', views.faq_view, name="faq"),
    path('webservice/', views.webservice, name="json_webservice"),
]

tk2_eclair/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('blog/', include('blog.urls') ),
    path('toko/', include('toko.urls'), name="pathToko"),
    path('beli/', include('beli_ikan.urls')),
    path('faq/', include('faq.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beli_ikan/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from toko.models import TokoIkan

class Ikan(models.Model):
    jenis = models.CharField(max_length = 100)
    foto = models.ImageField(upload_to='images/')
    harga = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(9223372036854775807)])
    deskripsi = models.TextField(max_length = 100)
    namaToko = models.ManyToManyField(TokoIkan)

    def __str__(self):
        return self.jenis

beli_ikan/forms.py
from django import forms
from . import models

class BuatIkan(forms.ModelForm):
    class Meta:
        model = models.Ikan
        fields = ['jenis', 'foto', 'harga', 'deskripsi', 'namaToko']

beli_ikan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from .models import Ikan
from django.core import serializers

def buat_ikan_view(request):
    if request.method == 'POST':
        form = forms.BuatIkan(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect ('beli_ikan:form_ikan')
    else:
        form = forms.BuatIkan()
        return render(request, 'buat_ikan.html', {'form_ikan':form})

def daftar_ikan_view(request):
    if request.method=='POST':
        form = forms.BuatIkan(request.POST)
        if form.is_valid():
            form.save()
        
    semua_ikan = Ikan.objects.all().order_by('jenis','harga')
    return render(request, "daftar_ikan.html", {'semua_ikan':semua_ikan})

def ambil_data_json(request):
    semua_ikan = Ikan.objects.all().order_by('jenis','harga')
    list_ikan = serializers.serialize('json', semua_ikan)
    return HttpResponse(list_ikan, content_type="application/json")

def hapus_Ikan(request, id):
    ikan_hapus = Ikan.objects.get(id=id)
    ikan_hapus.delete()
    return redirect('beli_ikan:form_ikan')

beli_ikan/templates/buat_ikan.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Daftar Ikan {% endblock %}
{% block isi %}
<link rel="stylesheet" href="{% static 'css/style_ikan.css' %}">
<script src="{% static 'js/attitude_ikan.js' %}"></script>

<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card form-buatIkan">
            <h5 class="card-header header-form">Tambah Ikan</h5>
            <div class="card-body">
                <form action="/beli/terima" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form_ikan.jenis|as_crispy_field }}
                    </div>
                    <div class="form-group">
                        {{ form_ikan.foto|as_crispy_field }}            
                    </div>
                    <div class="form-group">
                        {{ form_ikan.harga|as_crispy_field }}             
                    </div>
                    <div class="form-group">
                        {{ form_ikan.deskripsi|as_crispy_field }}          
                    </div>
                    <div class="form-group">
                        {{ form_ikan.namaToko|as_crispy_field }}
                    </div>
                    <button type="submit" class="btn btn-light" id="btn-tambahIkan">Tambah Ikan</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock isi %}

beli_ikan/templates/daftar_ikan.html
{% extends "base.html" %}
{% load static %}
{% block title %} Daftar Ikan {% endblock %}
{% block isi %}
<link rel="stylesheet" href="{% static 'css/style_ikan.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$(document).ready(() =>{
    $.ajax({
        method: 'GET',
        url: '/beli/datajson', 
        success: function(result){
          $("#card_ikan").empty();
          for(i=0; i < result.length ; i++) {
            let foto = result[i].fields.foto;
            let jenis = result[i].fields.jenis;
            let harga = result[i].fields.harga;
            let deskripsi = result[i].fields.deskripsi;
            let nama_toko = result[i].fields.namaToko;
            let prim_key = result[i].pk;
            console.log(prim_key);
    
            if(foto == undefined){
              foto = "No Foto"
            }
    
            if(jenis == undefined){
              jenis = "No Jenis"
            }
    
            if(harga == undefined){
              harga = "No harga"
            }
    
            if(deskripsi == undefined){
              deskripsi = "No deskripsi"
            }
    
            if(nama_toko == undefined){
              nama_toko = "No nama toko"
            }
    
            $("#card_ikan").append(
            "<div class='card' style='width: 18rem;'>" +
            "<img src=/media/" + foto + " class='card-img-top'" + "alt='image'>" + 
                "<div class='card-body'>" +
                    '<p class="card-text">' + jenis + '</p>' + 
                    '<p class="card-text">' + harga + '</p>' + 
                    '<p class="card-text">' + deskripsi + '</p>' + 
                    '<p class="card-text">' + nama_toko + '</p>' + 
                "{% if user.is_authenticated %}" + 
                '<p><a href=/beli/delete/' + prim_key + '>' + '<button type="submit" class="btn btn-danger btn_hapus_ikan">Hapus</button> </a></p>' +
                "{% endif %}" +
                "</div>"+
            "</div>");
            }
        }
    });

    $( ".card" ).hover(function() {
        $(this).addClass('shadow-lg').css('cursor', 'pointer'); 
    }, function() {
        $(this).removeClass('shadow-lg');
    }
    );
        
    $('.btn_hapus_ikan').click(function() {
        if(confirm("Yakin ingin menghapus ikan?")){
            return true;
        }else{
            return false;
        }
    });
});
</script>
<script src="{% static 'js/attitude_ikan.js' %}"></script>

<div id="loading">
</div>

{% if not user.is_authenticated %}
    <div>
        <h3>Login untuk menambah atau mengurangi ikan</h3>
    </div>
{% endif %}

{% if semua_ikan %}
<div class="row" id="card_ikan">
</div>
{% else %}
    <h1>Belum ada Ikan</h1>
{% endif %}

{% if user.is_authenticated %}
    <a href="{% url 'beli_ikan:terima' %}"><button type="button" class="btn btn-light" id="btn-buat_ikan">Daftar Ikan Baru</button></a>
{% endif %}

<div id="Jarak"></div>

{% endblock isi %}